### ISSUE TITLE
Could not initialize class org.bytedeco.javacpp.opencv_core

### ISSUE THREAD

**Issue by santhosh827** [bytedeco/javacv-examples#13]
Dear Team,

when final CvHaarClassifierCascade faceCascade = cvLoadHaarClassifierCascade(file.getCanonicalPath(), cvSize(0, 0));  line is executing i got below exception
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_core
please help

**Comment by saudet** [comment]
Please include ALL the JAR files in your class path.
