### ISSUE TITLE
Folder name "OpenCV2_Cookbook" is misleading

### ISSUE THREAD

**Issue by mkokho** [bytedeco/javacv-examples#15]
Hello there,

 Thank you for the good work on writing this examples - they do help in understanding of javacpp interface to OpenCV library. 

I noticed in the commits that you refactored example to work with OpenCV 3. Could you also change readme and the folder name? It will make it more attractive, I think.

Best,
Mikhail

**Comment by saudet** [comment]
Please send a pull request with the suggested changes! Thanks

**Comment by jpsacha** [comment]
OpenCV2 directories were renamed to OpenCV in last commit.
