### ISSUE TITLE
Please consider providing examples in Java

### ISSUE THREAD

**Issue by skarpushin** [bytedeco/javacv-examples#16]
[Here](https://github.com/bytedeco/javacv-examples/tree/master/OpenCV2_Cookbook#why-scala) you saying "Smaller boilerplate code makes examples easier to read and understand". It's not true. I don't know scala and I bet most JVM-based code is on Java. In order to understand your example I have to learn scala first, which I don't want to.

And I'm really wondering why **Java**CV has examples in Scala. Then you need to call it ScalaCV. Even Lightbend Akka documentation has examples in Scala and Java.

**Comment by saudet** [comment]
Yes, I totally agree, but someone needs to do it. If you would like to give it a try, let us know when you're having issues understanding the code and we'll help. Contributions are welcome!
