### ISSUE TITLE
some kind of issue in pylon when compiling,it's shows an missing jar file

### ISSUE THREAD

**Issue by suguna-mother** [bytedeco/javacv-examples#21]
**@jpsacha ,i have trying to execute pylon by using javacpp but it's shows an error like:**

ERROR] Failed to execute goal on project pylon-platform: Could not resolve dependencies for project org.bytedeco:pylon-platform:jar:1.0-1.5.1-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:Pylon:jar:1.0-1.5.1-SNAPSHOT, org.bytedeco:Pylon:jar:linux-x86_64:1.0-1.5.1-SNAPSHOT: Failure to find org.bytedeco:Pylon:jar:1.0-1.5.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles

**Comment by suguna-mother** [comment]
@jpsacha ,i need some help to solve this error.

**Comment by jpsacha** [comment]
You are trying to download dependency for Pylon. Pylon is not part of official javacpp-presets and is not being published. The Pylon present was never completed (I run into issues with C++ part of GeniCAM). You will need to build it yourself first localy. The most recent version (a bit old) is on this branch:
https://github.com/jpsacha/javacpp-presets/tree/wip/pylon
I no longer work on it tough. I moved on to Spinnaker/FLIR cameras.
