### ISSUE TITLE
Ex2ColorReduce report error

### ISSUE THREAD

**Issue by before31** [bytedeco/javacv-examples#23]
In chapter02,Ex2ColorReduce,when I run the example code, I received this error:
[info] running (fork) opencv_cookbook.chapter02.Ex2ColorReduce
[error] Exception in thread "main" java.lang.IndexOutOfBoundsException: 518400
[error]         at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:101)
[error]         at org.bytedeco.javacpp.indexer.UByteRawIndexer.getRaw(UByteRawIndexer.java:73)
[error]         at org.bytedeco.javacpp.indexer.UByteRawIndexer.get(UByteRawIndexer.java:76)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce$.$anonfun$colorReduce$1(Ex2ColorReduce.scala:48)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce$.$anonfun$colorReduce$1$adapted(Ex2ColorReduce.scala:46)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:190)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce$.colorReduce(Ex2ColorReduce.scala:46)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce$.delayedEndpoint$opencv_cookbook$chapter02$Ex2ColorReduce$1(Ex2ColorReduce.scala:28)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce$delayedInit$body.apply(Ex2ColorReduce.scala:22)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:76)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce$.main(Ex2ColorReduce.scala:22)
[error]         at opencv_cookbook.chapter02.Ex2ColorReduce.main(Ex2ColorReduce.scala)

**Comment by jpsacha** [comment]
For the reference here is the code that fails:
```scala
  def colorReduce(image: Mat, div: Int = 64): Mat = {

    val indexer = image.createIndexer().asInstanceOf[UByteIndexer]

    val nbElements = image.rows * image.cols * image.channels
    for (i <- 0 until nbElements) {
      val v = indexer.get(i) & 0xFF
      ...
```
It fails at `indexer.get(i)`. Looks like regression in JavaCPP. It stopped working with JavaCPP 1.5.4 (Open CV 4.4). Last commit it still works: https://github.com/bytedeco/javacv-examples/commit/78ed75e8ac8294f4f8505c1fdc212f1106d38c78

Something changed with implementation of JavaCPP's  `indexer.get(i)`. In the past `i=0` would get index 0, `i=1` index 1, `i=2` index 2 (figuratively speaking). You could go that way through all the pixels in the image. But now it jump by the stride, `i=1` gets `1440`, `i=2` gets `2880`, ... so it quickly causes `IndexOutOfBoundsException`. Here is a piece of code directly 'responsible' in `StrideIndexer`:
```java
    @Override public long index(long i) {
        return i * strides[0];
    }
```

@saudet is there some change how the indexing is interpreted now? Is it a bug in the indexer?

**Comment by saudet** [comment]
I see, that was "fixed" for consistency when @matteodg refactored that part. What we need to do for linear indexing now is to reindex with the `OneIndex`, so something like this should work:
```java
val indexer = image.createIndexer().reindex(new OneIndex(nbElements));
```

**Comment by jpsacha** [comment]
This gets a bit ugly in Scala as it need some casting and type hints to compile:
```scala
    val indexer =
      image
        .createIndexer()
        .asInstanceOf[Indexer] // cast needed to avoid: UByteRawIndexer cannot be cast to class scala.runtime.Nothing$
        .reindex[UByteIndexer](new OneIndex(nbElements))
```

**Comment by saudet** [comment]
I don't understand why Scala world trip on that. The reindex() method is part of the Indexer interface. Could you explain?

**Comment by jpsacha** [comment]
By the way, Java also has some problem with correct type derivation when when variable `indexer` type is not defined.
This compiles
```java
UByteIndexer indexer = image.createIndexer().reindex(new OneIndex(100));
indexer.get(0);
```
But if you skip the type and use use `var`
```java
var indexer = image.createIndexer().reindex(new OneIndex(nbElements));
indexer.get(0);
```
you will get error
```
java: cannot find symbol
   symbol:   method get(int)
   location: variable indexer of type org.bytedeco.javacpp.indexer.Indexer
```

**Comment by before31** [comment]
Thanks you two guys. The updated code works.
btw, is there any way to get the integer value directly , rather than performing 'value & 0xFF' every time after i got the unsigned byte value ?

**Comment by saudet** [comment]
> I updated the example to make it work. Maybe changing the code to avoid using `OneIndex` will help clarity but will require more nested loops - more boilerplate for better clarity :)

It's also possible to create a flat view of the Mat *before* creating an Indexer with something like this:
```java
UByteIndexer indexer = image.reshape(1, nbElements).createIndexer();
```

> By the way, Java also has some problem with correct type derivation when when variable `indexer` type is not defined.

No, it doesn't, it works fine for abstract methods of Indexer such as reindex() and getDouble(), which can be inferred at compile time, unlike the get() methods.

> Thanks you two guys. The updated code works.
> btw, is there any way to get the integer value directly , rather than performing 'value & 0xFF' every time after i got the unsigned byte value ?

We don't need those 0xFF, UByteIndexer does that, see http://bytedeco.org/news/2014/12/23/third-release/

**Comment by before31** [comment]
> We don't need those 0xFF, UByteIndexer does that, see http://bytedeco.org/news/2014/12/23/third-release/
Sorry for not describing the question clearly. 
First, I saw the 0xFF from the Ex2ColorReduce example, as below:
>   def colorReduce(image: Mat, div: Int = 64): Mat = {

    val indexer = image.createIndexer().asInstanceOf[UByteIndexer]

    val nbElements = image.rows * image.cols * image.channels
    for (i <- 0 until nbElements) {
      // Convert to integer, byte is treated as an unsigned value
      val v = indexer.get(i) & 0xFF
      ...
Is there a mistake? In fact, I tried to remove the 0xFF, and the code goes right.

In another scenario, I got the value through the following code:
>BytePointer bytePointer = image.ptr(j);
  byte value = bytePointer.get(0);
and the value is not the correct integer value but the unsigned byte. I must use 0xFF to convert it to integer.
Is there any way to get the integer value directly through the `BytePointer` ?

**Comment by saudet** [comment]
> and the value is not the correct integer value but the unsigned byte. I have to use 0xFF to convert it to integer.
> Is there any way to get the integer value directly through the `BytePointer` ?

It's easy enough to add getUnsigned()/putUnsigned() methods. Would you mind opening a pull request to that effect?

**Comment by before31** [comment]
> It's easy enough to add getUnsigned()/putUnsigned() methods. Would you mind opening a pull request to that effect?

Of course I will. Maybe I would do that in the next few days.
