### ISSUE TITLE
How to you convert the  cvSeq to Mat / Iplimage ?

### ISSUE THREAD

**Issue by shresthaankit7** [bytedeco/javacv-examples#8]
I need to get the minimum enclosing circle of the largest contour from my binary image. 
I have found largest contour but unable to get the enclosing circle.
C++ function defines as: 
minEnclosingCirlce( InputArray points, Point2f center, float radius ) 

I have the contour as cvSeq.
OpenCV says:
```java
org.bytedeco.javacpp.opencv_imgproc.minEnclosingCircle(@ByVal Mat arg0, @ByRef Point2f arg1, @ByRef FloatPointer arg2)
```
Now i need to convert the cvSeq contour to Mat / Iplimage 

Please help

**Comment by saudet** [comment]
Just use cvMinEnclosingCircle() that can accept a CvSeq.
